const units = {
    Energy: '(kcal)',
    Protein: '(g)',
    Carbohydrate: '(g)',
    'Sugars Total': '(g)',
    'Fiber Total Dietary': '(g)',
    'Total Fat': '(g)',
    'Fatty Acids Total Saturated': '(g)',
    'Fatty Acids Total Monounsaturated': '(g)',
    'Fatty Acids Total polyunsaturated': '(g)',
    Cholesterol: '(mg)',
    Retinol: '(mcg)',
    'Vitamin A RAE': '(mcg_RAE)',
    'Carotene Alpha': '(mcg)',
    'Carotene Beta': '(mcg)',
    'Cryptoxanthin Beta': '(mcg)',
    Lycopene: '(mcg)',
    'Lutein + Zeaxanthin': '(mcg)',
    Thiamin: '(mg)',
    Riboflavin: '(mg)',
    Niacin: '(mg)',
    'Vitamin B-6': '(mg)',
    'Folic Acid': '(mcg)',
    'Folate Food': '(mcg)',
    'Folate DFE': '(mcg_DFE)',
    'Folate Total': '(mcg)',
    'Choline Total': '(mg)',
    'Vitamin B-12': '(mcg)',
    'Vitamin B-12added': '(mcg)',
    'Vitamin C': '(mg)',
    'Vitamin D (D2 + D3)': '(mcg)',
    'Vitamin E (alpha-tocopherol)': '(mg)',
    'Vitamin Eadded': '(mg)',
    'Vitamin K (phylloquinone)': '(mcg)',
    Calcium: '(mg)',
    Phosphorus: '(mg)',
    Magnesium: '(mg)',
    Iron: '(mg)',
    Zinc: '(mg)',
    Copper: '(mg)',
    Selenium: '(mcg)',
    Potassium: '(mg)',
    Sodium: '(mg)',
    Caffeine: '(mg)',
    Theobromine: '(mg)',
    Alcohol: '(g)',
    '4:0': '(g)',
    '6:0': '(g)',
    '8:0': '(g)',
    '10:0': '(g)',
    '12:0': '(g)',
    '14:0': '(g)',
    '16:0': '(g)',
    '18:0': '(g)',
    '16:1': '(g)',
    '18:1': '(g)',
    '20:1': '(g)',
    '22:1': '(g)',
    '18:2': '(g)',
    '18:3': '(g)',
    '18:4': '(g)',
    '20:4': '(g)',
    '20:5 n-3': '(g)',
    '22:5 n-3': '(g)',
    '22:6 n-3': '(g)',
    Water: '(g)',
}

export default units
