export const HTTP_ADAPTER_HOST = 'HttpAdapterHost'
export const REFLECTOR = 'Reflector'
export const RESPONSE_PASSTHROUGH_METADATA = '__responsePassthrough__'
export const OMIT_RESPONSE_PROTECT_KEYS = 'omitResponseProtectKeys'
export const dbUtcFrmt = 'YYYY-MM-DD HH:mm:ss.sss'
